# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# JupyterHub docker-compose configuration file
version: "2"

services:
  hub-db:
    image: postgres:9.5
    container_name: jupyterhub-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${DB_VOLUME_CONTAINER}
    env_file:
      - secrets/postgres.env
    volumes:
      - "db:${DB_VOLUME_CONTAINER}"

  hub:
    depends_on:
      - hub-db
    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
      args:
        JUPYTERHUB_VERSION: ${JUPYTERHUB_VERSION}
    restart: always
    image: jupyterhub
    container_name: jupyterhub
    volumes:
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "data:${DATA_VOLUME_CONTAINER}"
      # Bind user list file
      - "${PWD}/secrets/userlist:/srv/jupyterhub/userlist"
      # Custom DockerHub config to be mounted on start instead of copied at build stage
      - "${PWD}/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py"
      # LetsEncrypt certificate
      - "secrets:/etc/letsencrypt"
    ports:
      - "7775:443"
    links:
      - hub-db
    environment:
      # All containers will join this network
      #DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}
      # JupyterHub will spawn this Notebook image for users
      #DOCKER_NOTEBOOK_IMAGE: ${LOCAL_NOTEBOOK_IMAGE}
      # Notebook directory inside user image
      #DOCKER_NOTEBOOK_DIR: ${DOCKER_NOTEBOOK_DIR}
      # Using this run command (optional)
      #DOCKER_SPAWN_CMD: ${DOCKER_SPAWN_CMD}
      # Postgres db info
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: hub-db
      # LetsEncrypt certificate
      SSL_KEY: "/etc/letsencrypt/privkey.pem"
      SSL_CERT: "/etc/letsencrypt/cert.pem"
      # Home directory for shared notebook subdirs
      DOCKER_SHARED_HOME_DIR: "${PWD}/shared"
    env_file:
      - secrets/postgres.env
      - secrets/oauth.env
      - secrets/docker.env
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py

volumes:
  data:
    external:
      name: ${DATA_VOLUME_HOST}
  secrets:
    external:
      name: ${SECRETS_VOLUME}
  db:
    external:
      name: ${DB_VOLUME_HOST}

networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}
